-- MySQL Script generated by MySQL Workbench
-- 09/20/14 12:09:25
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_sigho
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_sigho` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_sigho` ;

-- -----------------------------------------------------
-- Table `db_sigho`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sigho`.`departamento` (
  `iddepartamento` INT NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sigho`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sigho`.`municipio` (
  `idmunicipio` INT NOT NULL AUTO_INCREMENT,
  `municipio` VARCHAR(45) NOT NULL,
  `departamentoid` INT NOT NULL,
  PRIMARY KEY (`idmunicipio`),
  INDEX `fk_depto_municipio_idx` (`departamentoid` ASC),
  CONSTRAINT `fk_depto_municipio`
    FOREIGN KEY (`departamentoid`)
    REFERENCES `db_sigho`.`departamento` (`iddepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sigho`.`parametro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sigho`.`parametro` (
  `idparametro` INT NOT NULL,
  `parametro` VARCHAR(45) NOT NULL,
  `editable` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idparametro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sigho`.`valor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sigho`.`valor` (
  `idvalor` INT NOT NULL,
  `valor` VARCHAR(160) NOT NULL,
  `editable` TINYINT(1) NOT NULL DEFAULT 1,
  `parametroid` INT NOT NULL,
  PRIMARY KEY (`idvalor`),
  INDEX `fk_parametro_valor_idx` (`parametroid` ASC),
  CONSTRAINT `fk_parametro_valor`
    FOREIGN KEY (`parametroid`)
    REFERENCES `db_sigho`.`parametro` (`idparametro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sigho`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sigho`.`perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sigho`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sigho`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `identificacion` INT NOT NULL,
  `email_sena` VARCHAR(100) NULL,
  `email_misena` VARCHAR(100) NULL,
  `email` VARCHAR(100) NOT NULL,
  `celular` VARCHAR(15) NOT NULL,
  `telefono` VARCHAR(15) NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `municipioid` INT NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `nivel_formacion` INT NOT NULL,
  `tipo_documento` INT NOT NULL,
  `clave` VARCHAR(255) NOT NULL,
  `fecha_documento` DATE NOT NULL,
  `fecha_expiracion` DATE NOT NULL,
  `perfilid` INT NOT NULL,
  `horas_formacion` INT NOT NULL,
  `genero` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_municipio_usuario_idx` (`municipioid` ASC),
  INDEX `fk_valor_nivel_formacion_idx` (`nivel_formacion` ASC),
  INDEX `fk_valor_tipo_documento_idx` (`tipo_documento` ASC),
  INDEX `fk_perfil_usuario_idx` (`perfilid` ASC),
  INDEX `fk_valor_genero_idx` (`genero` ASC),
  CONSTRAINT `fk_municipio_usuario`
    FOREIGN KEY (`municipioid`)
    REFERENCES `db_sigho`.`municipio` (`idmunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_valor_nivel_formacion`
    FOREIGN KEY (`nivel_formacion`)
    REFERENCES `db_sigho`.`valor` (`idvalor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_valor_tipo_documento`
    FOREIGN KEY (`tipo_documento`)
    REFERENCES `db_sigho`.`valor` (`idvalor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfil_usuario`
    FOREIGN KEY (`perfilid`)
    REFERENCES `db_sigho`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_valor_genero`
    FOREIGN KEY (`genero`)
    REFERENCES `db_sigho`.`valor` (`idvalor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sigho`.`sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sigho`.`sede` (
  `idsede` INT NOT NULL AUTO_INCREMENT,
  `sede` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `municipioid` INT NOT NULL,
  PRIMARY KEY (`idsede`),
  INDEX `fk_municipio_sede_idx` (`municipioid` ASC),
  CONSTRAINT `fk_municipio_sede`
    FOREIGN KEY (`municipioid`)
    REFERENCES `db_sigho`.`municipio` (`idmunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sigho`.`ambiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sigho`.`ambiente` (
  `idambiente` INT NOT NULL AUTO_INCREMENT,
  `ambiente` VARCHAR(45) NOT NULL,
  `especializado` TINYINT(1) NOT NULL DEFAULT 0,
  `observacion` VARCHAR(255) NULL,
  `sedeid` INT NOT NULL,
  PRIMARY KEY (`idambiente`),
  INDEX `fk_sede_ambiente_idx` (`sedeid` ASC),
  CONSTRAINT `fk_sede_ambiente`
    FOREIGN KEY (`sedeid`)
    REFERENCES `db_sigho`.`sede` (`idsede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sigho`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sigho`.`grupo` (
  `idgrupo` INT NOT NULL AUTO_INCREMENT,
  `grupo` VARCHAR(45) NOT NULL,
  `agendado` TINYINT(1) NOT NULL DEFAULT 0,
  `vigente` TINYINT(1) NOT NULL DEFAULT 1,
  `director` INT NOT NULL,
  `ambienteid` INT NOT NULL,
  PRIMARY KEY (`idgrupo`),
  INDEX `fk_ambiente_grupo_idx` (`ambienteid` ASC),
  CONSTRAINT `fk_ambiente_grupo`
    FOREIGN KEY (`ambienteid`)
    REFERENCES `db_sigho`.`ambiente` (`idambiente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sigho`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sigho`.`area` (
  `idarea` INT NOT NULL AUTO_INCREMENT,
  `area` VARCHAR(45) NOT NULL,
  `usuarioid` INT NOT NULL,
  PRIMARY KEY (`idarea`),
  INDEX `fk_usuario_area_idx` (`usuarioid` ASC),
  CONSTRAINT `fk_usuario_area`
    FOREIGN KEY (`usuarioid`)
    REFERENCES `db_sigho`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sigho`.`programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sigho`.`programa` (
  `idprograma` INT NOT NULL,
  `programa` VARCHAR(100) NOT NULL,
  `version` SMALLINT NOT NULL,
  `areaid` INT NOT NULL,
  PRIMARY KEY (`idprograma`),
  INDEX `fk_area_programa_idx` (`areaid` ASC),
  CONSTRAINT `fk_area_programa`
    FOREIGN KEY (`areaid`)
    REFERENCES `db_sigho`.`area` (`idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sigho`.`jornada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sigho`.`jornada` (
  `idjornada` INT NOT NULL AUTO_INCREMENT,
  `jornada` VARCHAR(45) NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fin` TIME NOT NULL,
  `horas` INT NOT NULL,
  PRIMARY KEY (`idjornada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sigho`.`ficha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sigho`.`ficha` (
  `idficha` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `oferta` INT NOT NULL,
  `programaid` INT NOT NULL,
  `jornadaid` INT NOT NULL,
  `cant_aprendices` INT NOT NULL,
  PRIMARY KEY (`idficha`),
  INDEX `fk_valor_oferta_idx` (`oferta` ASC),
  INDEX `fk_programa_ficha_idx` (`programaid` ASC),
  INDEX `fk_jornada_ficha_idx` (`jornadaid` ASC),
  CONSTRAINT `fk_valor_oferta`
    FOREIGN KEY (`oferta`)
    REFERENCES `db_sigho`.`valor` (`idvalor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_programa_ficha`
    FOREIGN KEY (`programaid`)
    REFERENCES `db_sigho`.`programa` (`idprograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jornada_ficha`
    FOREIGN KEY (`jornadaid`)
    REFERENCES `db_sigho`.`jornada` (`idjornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sigho`.`disponiblidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sigho`.`disponiblidad` (
  `iddisponiblidad` INT NOT NULL AUTO_INCREMENT,
  `jornadaid` INT NOT NULL,
  `usuarioid` INT NOT NULL,
  `dia` INT NOT NULL,
  `disponible` TINYINT(1) NOT NULL DEFAULT 1,
  `grupoid` INT NULL,
  PRIMARY KEY (`iddisponiblidad`),
  INDEX `fk_jornada_disponibilidad_idx` (`jornadaid` ASC),
  INDEX `fk_usuario_disponibilidad_idx` (`usuarioid` ASC),
  INDEX `fk_valor_dia_idx` (`dia` ASC),
  CONSTRAINT `fk_jornada_disponibilidad`
    FOREIGN KEY (`jornadaid`)
    REFERENCES `db_sigho`.`jornada` (`idjornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_disponibilidad`
    FOREIGN KEY (`usuarioid`)
    REFERENCES `db_sigho`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_valor_dia`
    FOREIGN KEY (`dia`)
    REFERENCES `db_sigho`.`valor` (`idvalor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sigho`.`ficha_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sigho`.`ficha_grupo` (
  `idficha_grupo` INT NOT NULL AUTO_INCREMENT,
  `grupoid` INT NOT NULL,
  `fichaid` INT NOT NULL,
  `cant_aprendices` INT NOT NULL,
  PRIMARY KEY (`idficha_grupo`),
  INDEX `fk_ficha_grupo_idx` (`fichaid` ASC),
  INDEX `fk_grupo_ficha_idx` (`grupoid` ASC),
  CONSTRAINT `fk_ficha_grupo`
    FOREIGN KEY (`fichaid`)
    REFERENCES `db_sigho`.`ficha` (`idficha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_ficha`
    FOREIGN KEY (`grupoid`)
    REFERENCES `db_sigho`.`grupo` (`idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sigho`.`competencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sigho`.`competencia` (
  `idcompetencia` INT NOT NULL AUTO_INCREMENT,
  `usuarioid` INT NOT NULL,
  `programaid` INT NOT NULL,
  `calificado` TINYINT(1) NULL DEFAULT 0 COMMENT 'Si un instructor esta apto puede formar el 100% del programa.' /* comment truncated */ /*Si no solo puede formar algunas competencias.*/,
  PRIMARY KEY (`idcompetencia`),
  INDEX `fk_usuario_competencia_idx` (`usuarioid` ASC),
  INDEX `fk_programa_competencia_idx` (`programaid` ASC),
  CONSTRAINT `fk_usuario_competencia`
    FOREIGN KEY (`usuarioid`)
    REFERENCES `db_sigho`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_programa_competencia`
    FOREIGN KEY (`programaid`)
    REFERENCES `db_sigho`.`programa` (`idprograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sigho`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sigho`.`horario` (
  `idhorario` INT NOT NULL AUTO_INCREMENT,
  `grupoid` INT NOT NULL,
  `dia` INT NOT NULL,
  `jornadaid` INT NOT NULL,
  `usuarioid` INT NULL,
  `agendado` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idhorario`),
  INDEX `fk_grupo_horario_idx` (`grupoid` ASC),
  INDEX `fk_valor_dia_idx` (`dia` ASC),
  INDEX `fk_jornada_grupo_idx` (`jornadaid` ASC),
  CONSTRAINT `fk_grupo_horario`
    FOREIGN KEY (`grupoid`)
    REFERENCES `db_sigho`.`grupo` (`idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_valor_dia1`
    FOREIGN KEY (`dia`)
    REFERENCES `db_sigho`.`valor` (`idvalor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jornada_grupo`
    FOREIGN KEY (`jornadaid`)
    REFERENCES `db_sigho`.`jornada` (`idjornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sigho`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sigho`.`menu` (
  `idmenu` INT NOT NULL AUTO_INCREMENT,
  `menu` VARCHAR(45) NOT NULL,
  `menuid` INT NULL,
  `href` VARCHAR(255) NOT NULL DEFAULT '#',
  `icono` VARCHAR(150) NULL,
  `visible` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idmenu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sigho`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sigho`.`permiso` (
  `idpermiso` INT NOT NULL,
  `perfilid` INT NOT NULL,
  `menuid` INT NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idpermiso`),
  INDEX `fk_perfil_menu_idx` (`perfilid` ASC),
  INDEX `fk_menu_perfil_idx` (`menuid` ASC),
  CONSTRAINT `fk_perfil_menu`
    FOREIGN KEY (`perfilid`)
    REFERENCES `db_sigho`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_perfil`
    FOREIGN KEY (`menuid`)
    REFERENCES `db_sigho`.`menu` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
